# Generated by Django 3.2.6 on 2021-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
