# Generated by Django 3.2.6 on 2021-08-22 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
